# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
    # Array of commands to run before each build
    pre_cmd = []
    # Just plain old shell command. You could use `make` as well.
    cmd = "go build -ldflags=\"-X main.build=dev-air\" -o ./tmp/main ./cmd/main.go"
    # Array of commands to run after ^C
    post_cmd = []
    # Binary file yields from `cmd`.
    bin = "./tmp/main"
    # Customize binary, can setup environment variables when run your app.
    full_bin = "ADMIN_USERNAME=admin ADMIN_PASSWORD=1234123412341234 FEATURE_FLAG_DEFAULT=true ENABLE_TEST_AUTOMATION=true ./tmp/main"
    # Watch these filename extensions.
    include_ext = ["go", "tpl", "tmpl", "html"]
    # Ignore these filename extensions or directories.
    exclude_dir = ["data", "test", ".github", ".githooks", "docs", "node_modules", "app/web/node_modules"]
    # Watch these directories if you specified.
    include_dir = []
    # Watch these files.
    include_file = []
    # Exclude files.
    exclude_file = []
    # Exclude specific regular expressions.
    exclude_regex = ["_test\\.go"]
    # Exclude unchanged files.
    exclude_unchanged = true
    # Follow symlink for directories
    follow_symlink = true
    # This log file places in your tmp_dir.
    log = "air.log"
    # Poll files for changes instead of using fsnotify.
    poll = true
    # Poll interval (defaults to the minimum interval of 500ms).
    poll_interval = 500 # ms
    # It's not necessary to trigger build each time file changes if it's too frequent.
    delay = 0 # ms
    # Stop running old binary when build errors occur.
    stop_on_error = true
    # Send Interrupt signal before killing process (windows does not support this feature)
    send_interrupt = false
    # Delay after sending Interrupt signal
    kill_delay = 500 # nanosecond
    # Rerun binary or not
    rerun = false
    # Delay after each execution
    rerun_delay = 500
    # Add additional arguments when running binary (bin/full_bin)..
    args_bin = []

[log]
    # Show log time
    time = false
    # Only show main log (silences watcher, build, runner)
    main_only = false

[color]
    # Customize each part's color. If no color found, use the raw app log.
    main = "magenta"
    watcher = "cyan"
    build = "yellow"
    runner = "green"

[misc]
    # Delete tmp directory on exit
    clean_on_exit = true

[screen]
    clear_on_rebuild = true
    keep_scroll = true
