linters:
  disable-all: true
  enable: # https://golangci-lint.run/usage/linters
    - errcheck
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused
linter-settings:
  revive:
    enable-all-rules: true