services:
  blinkfile:
    build:
      dockerfile: .local/build.Dockerfile
      context: ..
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=1234123412341234
      - FEATURE_FLAG_LogAllAuthnCalls=1
      - ENABLE_TEST_AUTOMATION=true
    volumes:
      - blinkfile-data:/data
  blinkfile-hugo:
    build:
      dockerfile: ../.local/hugo.Dockerfile
      context: ../docs
    volumes:
      - ../docs:/src
  blinkfile-source:
    build:
      dockerfile: .local/build.Dockerfile
      target: source
      context: ..
    volumes:
      - blinkfile-src:/out_src
      - blinkfile-cache:/out_cache
  blinkfile-golangci-lint:
    image: golangci/golangci-lint:v1.55.2
    entrypoint: ["golangci-lint"]
    volumes:
      - blinkfile-src:/app
      - blinkfile-cache:/root/.cache
    working_dir: /app
  blinkfile-unit-test:
    build:
      dockerfile: .local/app.Dockerfile
      context: ..
    command: ["sh", "-c", "go test -coverprofile coverage.out ./... && go tool cover -html=coverage.out -o=coverage.html && cp coverage.* /out/"]
    volumes:
      - ../:/out
      - blinkfile-src:/src
      - blinkfile-cache:/cache

volumes:
  blinkfile-src:
  blinkfile-cache:
  blinkfile-data: