services:
  blinkfile:
    build:
      dockerfile: .local/build.Dockerfile
      context: ..
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=1234123412341234
      - FEATURE_FLAG_LogAllAuthnCalls=1
      - ENABLE_TEST_AUTOMATION=true
    volumes:
      - blinkfile-data:/data
  blinkfile-hugo:
    build:
      dockerfile: ../.local/hugo.Dockerfile
      context: ../docs
    volumes:
      - ../docs:/src
  blinkfile-unit-test:
    build:
      dockerfile: .local/unit-test.Dockerfile
      context: ..
    command: ["sh", "-c", "go test -coverprofile coverage.out ./... && go tool cover -html=coverage.out -o=coverage.html && cp coverage.* /out/"]
    volumes:
      - ../:/out
      - blinkfile-src:/src
      - blinkfile-cache:/cache

volumes:
  blinkfile-src:
    external: true
  blinkfile-cache:
    external: true
  blinkfile-data:
    external: false