name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'app/web/package.json'
      - run: cd app/web && npm ci # some directories in node_modules are embedded in Go binary
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'app/web/package.json'
      - run: cd app/web && npm ci # some directories in node_modules are embedded in Go binary
      - name: Run unit tests
        run: go test ./...
  build:
    needs: [lint, unit-test]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - uses: actions/setup-node@v4
      with:
        node-version-file: 'app/web/package.json'
    - run: cd app/web && npm ci # some directories in node_modules are embedded in Go binary
    - name: Build go binary
      run: CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o /app ./cmd/main.go
    - name: Upload go binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: binary
        path: /app
#  deploy:
#    needs: [build]
#    runs-on: ubuntu-22.04
#    steps:
#    - uses: docker/setup-buildx-action@v3
#    - name: Build and push release image
#      uses: docker/build-push-action@v5
#      with:
#        context: .
#        cache-from: type=gha
#        cache-to: type=gha
#        load: true
#        tags: blinkfile
#    - name: Acceptance test
#      run: cd test && make ci
#    - name: Docker login
#      uses: docker/login-action@v3
#      with:
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#    - name: Push image
#      uses: docker/build-push-action@v5
#      with:
#        context: .
#        push: true
#        tags: benjohns1/blinkfile:latest
