name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  source:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'app/web/package.json'
      - name: Install front-end javascript utilities
        run: cd app/web && npm ci # some directories in node_modules are embedded in Go binary
      - name: Upload source and installed dependencies
        uses: actions/upload-artifact@v4
        with:
          name: source
          path: ./
          compression-level: 6
  lint:
    runs-on: ubuntu-22.04
    needs: [source]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: source
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
  unit-test:
    runs-on: ubuntu-22.04
    needs: [source]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: source
      - name: Run unit tests
        run: go test ./...
  build:
    runs-on: ubuntu-22.04
    needs: [source]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: source
      - name: Build go binary
        run: CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o ./binary ./cmd/main.go
      - uses: docker/setup-buildx-action@v3
      - name: Build release image candidate
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.github/workflows/Dockerfile
          tags: blinkfile
          outputs: type=docker,dest=/tmp/image.tar
      - name: Upload release image candidate artifact
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: /tmp/image.tar
          compression-level: 0
  acceptance-test:
    runs-on: ubuntu-22.04
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: image
          path: /tmp
      - name: Load release image candidate
        run: docker load --input /tmp/image.tar
      - uses: actions/download-artifact@v4
        with:
          name: source
      - name: Acceptance test
        run: cd test && make ci
  deploy:
    runs-on: ubuntu-22.04
    needs: [lint,unit-test,build,acceptance-test]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: image
          path: /tmp
      - name: Load release image candidate
        run: docker load --input /tmp/image.tar
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: benjohns1/blinkfile:latest
