name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths: ["**", "!docs/**", "!README.md", "!LICENSE", "!.husky/**", "!.local/**", "!.github/workflows/docs.yml"]
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "docker-image"
  cancel-in-progress: true

jobs:
  source:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'app/web/package.json'
      - name: Install front-end javascript utilities
        run: cd app/web && npm ci && npm audit signatures # some directories in node_modules are embedded in Go binary
      - name: Install go dependencies
        run: go mod download
      - name: Upload source and installed dependencies
        uses: actions/upload-artifact@v4
        with:
          name: source
          path: |
            ./
            !test/
          if-no-files-found: error
  commitlint-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - name: Install tooling
        run: npm ci && npm audit signatures
      - name: Verify last commit
        run: npm run commitlint -- --from=HEAD~1 --to HEAD --verbose
      - name: Calculate & output version
        id: versioning
        run: npx commit-and-tag-version && echo ::set-output name=version::$(cat VERSION)
    outputs:
      version: ${{ steps.versioning.outputs.version}}
  lint:
    runs-on: ubuntu-22.04
    needs: source
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: source
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
  unit-test:
    runs-on: ubuntu-22.04
    needs: source
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: source
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Run unit tests
        run: go test ./...
  build:
    runs-on: ubuntu-22.04
    needs: [source,commitlint-version]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: source
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Build go binary
        run: |
          echo Building app version ${{needs.commitlint-version.outputs.version}} candidate
          CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o ./binary ./cmd/main.go
      - uses: docker/setup-buildx-action@v3
      - name: Build release image candidate
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.github/workflows/Dockerfile
          outputs: type=docker,dest=/tmp/app-candidate-image.tar
          tags: blinkfile-candidate
      - name: Upload app image candidate artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-candidate-image
          path: /tmp/app-candidate-image.tar
          compression-level: 0
          if-no-files-found: error
  acceptance-test-source:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Upload source and installed dependencies
        uses: actions/upload-artifact@v4
        with:
          name: acceptance-test-source
          path: test/
          if-no-files-found: error
  acceptance-test:
    runs-on: ubuntu-22.04
    needs: [build,acceptance-test-source]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-candidate-image
          path: /tmp
      - name: Load app image candidate
        run: docker load --input /tmp/app-candidate-image.tar
      - uses: actions/download-artifact@v4
        with:
          name: acceptance-test-source
      - uses: docker/setup-buildx-action@v3
      - name: Build acceptance-test runner image
        uses: docker/build-push-action@v5
        with:
          context: ./cypress
          load: true
          tags: blinkfile-acceptance-test-runner
          cache-from: type=gha
          cache-to: type=gha
      - name: Run acceptance tests
        run: docker compose up --exit-code-from acceptance-test-runner
  deploy:
    runs-on: ubuntu-22.04
    needs: [lint,unit-test,build,acceptance-test]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-candidate-image
          path: /tmp
      - name: Load app image candidate
        run: docker load --input /tmp/app-candidate-image.tar
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Tag & push image
        run: |
          docker tag blinkfile-candidate benjohns1/blinkfile:latest
          docker push -a benjohns1/blinkfile
