name: Lint
on: [workflow_call]
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd app/web && npm ci
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
